### ISSUE TITLE
NameError: name 'redtype' is not defined

### ISSUE THREAD

**Issue by viksra** [RainbowRoxxers/Discorddit-Webhook#3]
I keep getting errors from the bot, which lead to the script stopping entirely and me having to retype the command to execute it. The bot has proven very unreliable so far. I have it configured to pull posts from two subreddits: r/nyc and r/asknyc. The bot works for a while, then stops with the error below:

```
Posted I wonder if they ever found her.
Code 204

Traceback (most recent call last):
  File "C:\Users\me\Desktop\reddit\Discorddit-Webhook-master\Discorddit.py", line 28, in <module>
    disModule.postDiscordPost(newPost, webhookURL, img, colors[subreddits.index(
subreddit)])
  File "C:\Users\me\Desktop\reddit\Discorddit-Webhook-master\disModule.py", line 65, in postDiscordPost
    message = developDiscordPost(argData, argImage, argColor)
  File "C:\Users\me\Desktop\reddit\Discorddit-Webhook-master\disModule.py", line 36, in developDiscordPost
    elif redtype == 3:
NameError: name 'redtype' is not defined
```

**Comment by RainbowRoxxers** [comment]
Hey sorry for missing this. I know its no use to you now but its clear from the error logs that your not using my version but a fork for this program. So I wouldn't be able to help you. Sorry for not noticing this earlier.
